## NumPy Basics

* NumPy (Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.
* Numpy is also incredibly fast, as it has bindings to C libraries.
* We will only learn the basics of NumPy.

### Using NumPy

Importing it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We will not cover them all but instead we will focus on some of the most important aspects of NumPy: vectors, arrays, matrices and number generation. Let's start by discussing arrays.

### NumPy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavours: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

### Creating NumPy Arrays

#### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built in Methods

There are lots of built-in ways to generate Arrays.

#### arange

Return evenly spaced values with a given interval.

In [6]:
np.arange(0, 10)  # Similar to range in python

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

#### Zeros and ones

Generate arrays of zeros or ones

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Linspace

Return evenly spaced numbers over a specified interval.

In [12]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

#### eye

Creates an identity matrix.

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Random

Numpy also has lots of ways to create random number arrays:

##### rand

Create an array of the given shape and populate it with random samples from a uniform distribution over `[0,1]`.

In [15]:
np.random.rand(5)

array([0.61173824, 0.35637962, 0.55801284, 0.3675026 , 0.09754062])

In [16]:
np.random.rand(5,5)

array([[0.77647668, 0.62926515, 0.29382222, 0.8597856 , 0.13632135],
       [0.10105975, 0.30398427, 0.51052503, 0.18977495, 0.48294141],
       [0.82358141, 0.8227933 , 0.73147958, 0.47302596, 0.60618934],
       [0.76819576, 0.93753044, 0.04652359, 0.81154957, 0.00951864],
       [0.02854777, 0.16159464, 0.36577931, 0.93051616, 0.36071719]])

##### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [17]:
np.random.randn(2)

array([ 0.73477382, -0.93305503])

In [18]:
np.random.randn(5,5)

array([[ 1.67688201, -0.1211751 , -0.48767955,  1.20683559, -0.3067771 ],
       [ 0.23701923, -0.89232899,  0.2407249 ,  0.47449397, -0.22262407],
       [-0.45747806,  0.6277846 ,  0.64504266,  0.08773341, -0.5802913 ],
       [ 0.3698485 , -0.00273602, -2.1446383 , -0.27479482,  0.66904616],
       [-1.17220652,  0.7531349 ,  0.55311394, -0.3984717 ,  1.37334334]])

##### randint

Return random integers from `low` (inclusive) to `high` (exclusive).

In [19]:
np.random.randint(1,100)

42

In [20]:
np.random.randint(1, 100, 10)

array([96, 30, 13, 51, 18, 43, 67,  5, 14, 46], dtype=int32)

#### Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [21]:
arr = np.arange(25)
arr24 = np.arange(24)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([26,  8, 20,  6, 17,  0, 39, 35,  0, 28], dtype=int32)

#### Reshape

Returns an array containing the same data with a new shape.

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr24.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

##### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax.

In [26]:
ranarr

array([26,  8, 20,  6, 17,  0, 39, 35,  0, 28], dtype=int32)

In [27]:
ranarr.max()

np.int32(39)

In [28]:
ranarr.argmax()

np.int64(6)

In [29]:
ranarr.min()

np.int32(0)

In [30]:
ranarr.argmin()

np.int64(5)

#### Shape

Shape is an attribute that arrays have (not a method):

In [31]:
# Vector
arr.shape

(25,)

In [32]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [34]:
arr.reshape(1,25).shape

(1, 25)

In [35]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [36]:
arr.reshape(25,1).shape

(25, 1)

#### dtype

You can also grab the datatype of the object in the array:

In [37]:
arr.dtype

dtype('int64')

### Numpy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [38]:
# Creating sample array
arr = np.arange(0,11)

In [39]:
# Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket Indexing and Selection

The simplest way to pick one or some elements of an array looks very similar to python lists:

In [40]:
# Get a value at an index
arr[8]

np.int64(8)

In [41]:
# Get values in a range
arr[1:5]  # Slice

array([1, 2, 3, 4])

In [42]:
# Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

#### Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [43]:
# Setting a value with index range (Broadcasting)
arr[0:5] = 100

# Show 
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [44]:
# Reset array
arr = np.arange(0,11)

# Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Broadcasting

In [45]:
# Important notes on Slices
slice_of_arr = arr[0:6]

# Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [46]:
# Change slice
slice_of_arr[:] = 99

# Show slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

#### Broadcasting (Dangers)

Now note the changes also occurs in our original array!

In [47]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

#### Copying

In [48]:
# To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [49]:
slice_of_arr_2 = arr_copy[0:5]
slice_of_arr_2

array([99, 99, 99, 99, 99])

In [50]:
slice_of_arr_2[:] = 1000

In [53]:
slice_of_arr_2, arr_copy, arr

(array([1000, 1000, 1000, 1000, 1000]),
 array([1000, 1000, 1000, 1000, 1000,   99,    6,    7,    8,    9,   10]),
 array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10]))

#### Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row, col]**. I recommend usually the comma notation for clarity.

In [54]:
arr_2d = np.array(([5,10,15], [20,25,30], [35,40,45]))

# Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
# Indexing row
arr_2d[1]

array([20, 25, 30])

In [59]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][2]

np.int64(30)

In [60]:
# Getting individual element value
arr_2d[1,2]

np.int64(30)

In [61]:
# 2D array slicing

# Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [62]:
# Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [63]:
# Shape bottom row
arr_2d[2, :]

array([35, 40, 45])

#### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order, to show this , let's quickly build out a numpy array:

In [64]:
# Set up matrix
arr2d = np.zeros((10,10))

In [65]:
# Length of array
arr_length = arr2d.shape[1]

In [68]:
# Set up array
for i in range(arr_length):
    arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [69]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [70]:
# Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

#### More Indexing Help

Indexing a 2D matrix can be a bit confusing at first, especially when you start to add in step size.

#### Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [71]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [73]:
bool_arr = arr > 4  # Sometimes called a mask

In [74]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [75]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [76]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
x = 5
arr[arr > x]

array([ 6,  7,  8,  9, 10])

#### Numpy Operations

##### Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [79]:
arr = np.arange(0,10)

In [80]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [81]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [82]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [83]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Users\Aditya\AppData\Local\Temp\ipykernel_13708\2878212635.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [84]:
# Also warning, but not an error instead infinity
1/arr

C:\Users\Aditya\AppData\Local\Temp\ipykernel_13708\1360216608.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [85]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

#### Universal Array Functions

Numpy comes with many *universal array functions*, which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [86]:
# Taking square roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [87]:
# Calculating exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [88]:
np.max(arr) # same as arr.max()

np.int64(9)

In [89]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [92]:
np.log(arr)

C:\Users\Aditya\AppData\Local\Temp\ipykernel_13708\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [93]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])